### ISSUE TITLE
Please provide a Docker version or guide me on how to compile it on CentOS 7. Your GLIBC version is too high.

### ISSUE THREAD

**Issue by hcymysql** [planetscale/schemadiff#15]
Please provide a Docker version or guide me on how to compile it on CentOS 7. Your GLIBC version is too high.

**Comment by hcymysql** [comment]
```
# ./schemadiff 
./schemadiff: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./schemadiff)
./schemadiff: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./schemadiff)
```

**Comment by dbussink** [comment]
This should be fixed in #16. 

For self-compiling, you should be able to run `make` to build it.

**Comment by dbussink** [comment]
There's now a 1.1 release which is built with `CGO_ENABLED=0` which means there's no glibc dependency anymore.

**Comment by hcymysql** [comment]
thanks
